[project]
name = "tusir"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bssir[all]",
]

[tool.uv.sources]
bssir = { git = "https://github.com/Iran-Open-Data/BSSIR" }
