# Package Name
package_name: TUSIR

# Local Directory
local_dir: Data
in_root: true

# Years (list of years or range in for of: "first_year - last_year")
years: [1387, 1393, 1398]

# Local Settings
local_settings: config/tusir_settings.yaml

# Folder Names
folder_names:
  cached: TUSIR/_cache
  metadata: TUSIR/_metadata
  original: TUSIR/1_original
  unpacked: TUSIR/2_unpacked
  extracted: TUSIR/3_extracted
  cleaned: TUSIR/4_cleaned
  external: External_Data
  maps: Maps
